version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - db-data:/var/lib/sqlite3/data:rw
    ports:
      - "8080:8080"
    networks:
      - app-network

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:8080"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    networks:
      - app-network

  url-fetcher:
    container_name: ngrok_public_url
    image: curlimages/curl
    command: "sh -c 'sleep 5 && curl http://ngrok:4040/api/tunnels'"
    depends_on:
      - ngrok
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db-data:
